### PR TITLE
Do not call Vfs functions in JPS module [2019.3]

### LINKED ISSUE #76: Attempting to build a project fails with NoClassDefFoundError on IDEA 2019.3 EAP
Please see the discussion here for further details:

https://youtrack.jetbrains.net/issue/KT-33899

### PR DESCRIPTION
**Pull request by tpasternak**
New IntelliJ version (2019.3) doesn't allow to call Vfs functions in
JPS module. This means that the paths has to be converted to URLs
during configuration.

There's no need to call `urlToPath` in ThriftBuilder because:

1. compilerPath is now passed to ThriftConfig constructor as URL

2. outputDir was already crated as URL:
```
      final String url = VfsUtil.pathToUrl(dir);
      final VirtualFile file = VirtualFileManager.getInstance().findFileByUrl(url);

      myGenerator.setOutputDir(file == null ? url : file.getUrl());
```

fixes #76

### CODE REVIEW

File: plugin-jps/src/com/intellij/plugins/thrift/jps/ThriftBuilder.java [hunk 1]
```diff
@@ -46,8 +46,7 @@ public ExitCode build(CompileContext context,
                         ModuleLevelBuilder.OutputConsumer outputConsumer) throws ProjectBuildException, IOException {
     ThriftConfig thriftConfig = ThriftConfig.getSettings(context.getProjectDescriptor().getProject());
 
-    final String compiler = VfsUtil.urlToPath(thriftConfig.getCompilerPath());
```
Comment (Sohamr) [inline plugin-jps/src/com/intellij/plugins/thrift/jps/ThriftBuilder.java]: nit: would be good to remove `import com.intellij.openapi.vfs.VfsUtil;` from imports since it is not used anymore.

**Comment by tpasternak** [comment]
I just noticed there was a mistake - outputDir path was passed to thirft CLI as URL. Now I still convert it in builder, but without `VfsUtils` call

**Comment by tpasternak** [comment]
Guys, what do you think about merging this PR and releasing a new version? Just to let people who use 2019.3 BETA test it.

**Comment by fkorotkov** [comment]
I'm trying to move the plugin to build with https://github.com/JetBrains/gradle-intellij-plugin and add CI to make it easier to contribute. I'll try to finish it today and anyways will merge the request and build a new version of the plugin either with Gradle or with IntelliJ like right now.

**Comment by tpasternak** [comment]
Thank you!

And yes, migration to gradle would make development a lot convenient. Thanks for this, too.
